"""initialize tables v1

Revision ID: eb9cdc2d00fd
Revises: 
Create Date: 2022-03-31 07:57:47.082270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9cdc2d00fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tamil_dubbed_movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('tamilyogi_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tamil_hd_movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('tamilyogi_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tamil_new_movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('tamilyogi_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tamil_new_movie')
    op.drop_table('tamil_hd_movie')
    op.drop_table('tamil_dubbed_movie')
    # ### end Alembic commands ###
